# CST3240 Touchscreen with Virtual Touch Buttons
# This example demonstrates creating touch-sensitive regions

esphome:
  name: cst3240-buttons

esp32:
  board: esp32dev

wifi:
  ssid: "YourWiFiNetwork"
  password: "YourWiFiPassword"

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:

# Enable OTA updates
ota:
  - platform: esphome

# External component configuration
external_components:
  - source: github://shyndman/esphome-cst3240
    components: [cst3240]

# I2C Bus Configuration
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

# SPI Bus for Display
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

# Display Configuration
display:
  - platform: ili9xxx
    id: my_display
    model: ILI9341
    dimensions: 320x240
    cs_pin: GPIO5
    dc_pin: GPIO2
    reset_pin: GPIO4
    invert_colors: false

# Touchscreen Configuration
touchscreen:
  - platform: cst3240
    id: my_touchscreen
    display: my_display
    interrupt_pin: GPIO15
    reset_pin: GPIO16
    calibration:
      x_min: 0
      x_max: 320
      y_min: 0
      y_max: 240
    transform:
      mirror_x: false
      mirror_y: false
      swap_xy: false

# Virtual Touch Buttons
binary_sensor:
  # Home button (bottom left corner)
  - platform: touchscreen
    name: "Home Button"
    touchscreen_id: my_touchscreen
    x_min: 0
    x_max: 80
    y_min: 200
    y_max: 240
    on_press:
      then:
        - logger.log: "Home button pressed"

  # Settings button (bottom right corner)
  - platform: touchscreen
    name: "Settings Button"
    touchscreen_id: my_touchscreen
    x_min: 240
    x_max: 320
    y_min: 200
    y_max: 240
    on_press:
      then:
        - logger.log: "Settings button pressed"

  # Main area (center of screen)
  - platform: touchscreen
    name: "Main Area"
    touchscreen_id: my_touchscreen
    x_min: 80
    x_max: 240
    y_min: 40
    y_max: 200
    on_press:
      then:
        - logger.log: "Main area touched"

  # Top notification bar
  - platform: touchscreen
    name: "Notification Bar"
    touchscreen_id: my_touchscreen
    x_min: 0
    x_max: 320
    y_min: 0
    y_max: 40
    on_press:
      then:
        - logger.log: "Notification bar touched"

  # CST3240 specific virtual button
  - platform: cst3240
    cst3240_id: my_touchscreen
    name: "CST3240 Virtual Button"
    on_press:
      then:
        - logger.log: "CST3240 virtual button activated"

# LED indicator for button presses
light:
  - platform: status_led
    name: "Touch Indicator"
    pin: GPIO26